import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b7c8e1",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary-container": "#98805d",
        "surface-container-highest": "#e0e3e5",
        "primary": "#000000",
        "on-error-container": "#93000a",
        "on-primary-container": "#7c839b",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#574425",
        "surface": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "on-primary-fixed": "#131b2e",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#dec29a",
        "on-secondary-fixed": "#0b1c30",
        "error": "#ba1a1a",
        "tertiary-container": "#271901",
        "surface-container": "#eceef0",
        "outline-variant": "#c6c6cd",
        "inverse-primary": "#bec6e0",
        "background": "#f7f9fb",
        "primary-container": "#131b2e",
        "tertiary": "#000000",
        "primary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#45464d",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-variant": "#e0e3e5",
        "secondary": "#505f76",
        "secondary-container": "#d0e1fb",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed": "#fcdeb5",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#271901",
        "on-secondary-container": "#54647a",
        "surface-container-low": "#f2f4f6",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed": "#d3e4fe",
        "outline": "#76777d",
        "surface-tint": "#565e74",
        "amber-500": "#f59e0b",
        "amber-50": "#fffbeb",
        "amber-200": "#fde68a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Source Serif 4", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Source Serif 4", "serif"],
        "citation": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Source Serif 4", "serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
