import json
from datetime import datetime, timezone
from pydantic import BaseModel

class AuditTrail(BaseModel):
    export_version: str = "1.0"
    generated_at: str
    tool_name: str = "Compliance Lens by Norrin"
    legal_disclaimer: str
    product_description: str
    classification: dict
    validation: dict
    context_sources: list[dict]
    followup_questions: list[str]
    what_would_change_this: str
    recommended_next_steps: list[str]

def build_audit_trail(
    product_description: str,
    orchestrator_response: dict
) -> AuditTrail:
    classification = orchestrator_response["classification"]
    validation = orchestrator_response["validation"]
    context = orchestrator_response["context_used"]
    
    # Separate EU Act from Norrin sources for transparency
    eu_sources = [c for c in context.get("eu_act_chunks", [])]
    norrin_sources = [c for c in context.get("norrin_chunks", [])]
    
    all_sources = []
    for s in eu_sources:
        all_sources.append({
            "source_type": "EU AI Act (Official Text)",
            "article": s.get("article", ""),
            "title": s.get("title", ""),
            "relevance_score": s.get("relevance_score", 0),
            "excerpt": s.get("text", "")[:300] + "..." if len(s.get("text", "")) > 300 else s.get("text", "")
        })
    for s in norrin_sources:
        all_sources.append({
            "source_type": "Norrin Internal Guidance (Interpretive — Not Legally Binding)",
            "article": s.get("article", ""),
            "title": s.get("title", ""),
            "relevance_score": s.get("relevance_score", 0),
            "excerpt": s.get("text", "")[:300] + "..." if len(s.get("text", "")) > 300 else s.get("text", "")
        })
    
    return AuditTrail(
        generated_at=datetime.now(timezone.utc).isoformat(),
        legal_disclaimer=(
            "This document is generated by an AI system (Compliance Lens, developed by Norrin) "
            "and does not constitute legal advice. The EU AI Act is subject to evolving "
            "interpretation and no binding court precedent currently exists. This output "
            "should be reviewed by qualified legal counsel before any compliance decisions "
            "are made. Classifications with a confidence score below 70 are particularly "
            "subject to legal uncertainty and require expert review."
        ),
        product_description=product_description,
        classification={
            "risk_tier": classification.get("tier", "UNKNOWN"),
            "confidence_basis": classification.get("confidence_basis", ""),
            "rationale": classification.get("rationale", ""),
            "legal_citations": classification.get("citations", []),
            "compliance_obligations": classification.get("obligations", [])
        },
        validation={
            "confidence_score": validation.get("confidence_score", 0),
            "validator_agrees": validation.get("agrees_with_tier", False),
            "validator_concerns": validation.get("concerns", ""),
            "alternative_tier_possible": validation.get("alternative_tier_possible", False)
        },
        context_sources=all_sources,
        followup_questions=validation.get("suggested_followup_questions", []),
        what_would_change_this=classification.get("what_would_change_this", ""),
        recommended_next_steps=classification.get("obligations", []) + [
            "Review this classification with qualified legal counsel",
            "Address all open questions identified by the Validator before filing",
            "Document your classification rationale in your technical file"
        ]
    )

def export_to_json(audit_trail: AuditTrail) -> str:
    return json.dumps(audit_trail.model_dump(), indent=2, ensure_ascii=False)
