from .retrieval import RetrievalAgent
from .classifier import ClassifierAgent
from .validator import ValidatorAgent

class Orchestrator:
    def __init__(self):
        self.retrieval = RetrievalAgent()
        self.classifier = ClassifierAgent()
        self.validator = ValidatorAgent()

    async def classify_product(self, description: str) -> dict:
        context = await self.retrieval.search(description)
        classification = await self.classifier.classify(description, context)
        validation = await self.validator.validate(description, context, classification)
        return {
            "classification": classification,
            "validation": validation,
            "context_used": context,
            "disclaimer": self._disclaimer()
        }

    async def answer_question(self, question: str) -> dict:
        context = await self.retrieval.search(question)
        answer = await self.classifier.answer(question, context)
        return {
            "answer": answer,
            "context_used": context,
            "disclaimer": self._disclaimer()
        }

    def _disclaimer(self) -> str:
        return (
            "This output is generated by an AI system and is not legal advice. "
            "Classifications should be reviewed by qualified legal counsel before "
            "any compliance decisions are made. EU AI Act interpretation is evolving "
            "and no court precedent currently exists."
        )
