from .retrieval import RetrievalAgent
from .classifier import ClassifierAgent
from .validator import ValidatorAgent
import time

class Orchestrator:
    def __init__(self):
        self.retrieval = RetrievalAgent()
        self.classifier = ClassifierAgent()
        self.validator = ValidatorAgent()

    async def classify_product(self, description: str) -> dict:
        t0 = time.time()
        context = await self.retrieval.search(description)
        t_retrieval = (time.time() - t0) * 1000
        
        t1 = time.time()
        classification = await self.classifier.classify(description, context)
        t_classifier = (time.time() - t1) * 1000
        
        t2 = time.time()
        validation = await self.validator.validate(description, context, classification)
        t_validator = (time.time() - t2) * 1000
        
        return {
            "classification": classification,
            "validation": validation,
            "context_used": context,
            "metrics": {
                "retrieval_ms": round(t_retrieval, 2),
                "classifier_ms": round(t_classifier, 2),
                "validator_ms": round(t_validator, 2),
                "orchestrator_total_ms": round(t_retrieval + t_classifier + t_validator, 2)
            },
            "disclaimer": self._disclaimer()
        }

    async def answer_question(self, question: str) -> dict:
        context = await self.retrieval.search(question)
        answer = await self.classifier.answer(question, context)
        return {
            "answer": answer,
            "context_used": context,
            "disclaimer": self._disclaimer()
        }

    def _disclaimer(self) -> str:
        return (
            "This output is generated by an AI system and is not legal advice. "
            "Classifications should be reviewed by qualified legal counsel before "
            "any compliance decisions are made. EU AI Act interpretation is evolving "
            "and no court precedent currently exists."
        )
